### PR TITLE
add Actions workflow to push model to Replicate

### PR DESCRIPTION
**Pull request by zeke**
This PR adds a GitHub Actions workflow that  `cog push`es the latest changes to https://replicate.com/replicate/dreambooth whenever a change lands on the main branch.

We may eventually want some checks in place to more selectively publish when certain conditions are met, but this seems like a good place to start, just to get something working.

Resolves https://github.com/replicate/dreambooth/issues/17

## To Do

- [x] Add `REPLICATE_API_TOKEN` to repo secrets
- [x] Test the workflow on https://replicate.com/zeke/dreambooth (https://github.com/replicate/dreambooth/actions/runs/3654770543/jobs/6175479257)
- [x] Update the workflow file to publish to replicate/dreambooth
- [ ] Create https://replicate.com/replicate/dreambooth-staging
- [ ] Update workflow to download weights
- [ ] Test with https://replicate.com/replicate/dreambooth-staging
- [ ] Get review from the team
- [ ] Merge

### CODE REVIEW

**Comment by zeke** [comment]
This is still ready for eyes.

**Comment by zeke** [comment]
Bump @chenxwh @anotherjesse

**Review by evilstreak — APPROVED** [review]
Great!

**Comment by bfirsh** [comment]
Do we want lots and lots of versions? Versions feel more heavyweight and intentional than a commit. Something like a release.

For example, we might merge three PRs in quick succession. We probably want a single version with the changes bundled up for that so users don't have to wade through and make sense of a long list of versions.

If we make a change to the readme or something else that doesn't affect the behavior of the model, we don't want to push that as a no-op version.

Perhaps we should have a "push" action that we run manually rather than it run on every commit?

**Comment by zeke** [comment]
Perhaps we should have a "push" action that we run manually rather than it run on every commit?

Good call. I'll work on that.

**Comment by zeke** [comment]
I renamed the workflow to "push" and updated it to use a `workflow_dispatch` trigger so we can manually kick it off, and publish to `replicate/dreambooth-staging` or `replicate/dreambooth`: https://github.com/replicate/dreambooth/pull/16/commits/7738fa46416317b405bd32f5245a9e6be3cf579a

Still need to figure out how to make `cog run script/download-weights` happen though. See https://github.com/replicate/cog/issues/867

This is not as ready to go as I first thought. Moving it back to draft.

**Comment by zeke** [comment]
We now have an official GitHub Action for this sort of thing: https://github.com/replicate/setup-cog

This DreamBooth project is not likely to be actively maintained any more now that [fine-tuning with SDXL](https://replicate.com/blog/fine-tune-sdxl) is the new hotness, so I'm closing this PR.

**Pull request closed without merging**
